# Generated by Django 6.1 on 2026-08-24 20:24

import apps.accounts.validators
import django.contrib.auth.models
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Bu foydalanuvchi nomi band.'}, help_text='3-30 belgi. Harf bilan boshlanadi; harflar, raqamlar va pastki chiziq.', max_length=30, unique=True, validators=[apps.accounts.validators.validate_username], verbose_name='foydalanuvchi nomi')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name="o'zi haqida")),
                ('karma_cached', models.IntegerField(db_index=True, default=0, verbose_name='karma (keshlangan)')),
                ('is_expert', models.BooleanField(db_index=True, default=False, verbose_name='ekspert')),
                ('is_banned', models.BooleanField(default=False, verbose_name='bloklangan')),
                ('banned_until', models.DateTimeField(blank=True, help_text="Bo'sh bo'lsa — doimiy blok. D2-T11 (uch ogohlantirish) ishlatadi.", null=True, verbose_name='blok tugashi')),
                ('ban_reason', models.CharField(blank=True, max_length=200, verbose_name='blok sababi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_uniq', violation_error_message='Bu foydalanuvchi nomi band.')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
