# Generated by Django 6.1 on 2026-08-28 18:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oldingi_username',
            field=models.CharField(blank=True, editable=False, help_text="Eski havolalar (/@eski/) shu orqali yangisiga yo'naltiriladi.", max_length=30, verbose_name='oldingi nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_ozgartirilgan',
            field=models.DateTimeField(blank=True, editable=False, help_text="To'ldirilgan bo'lsa — nom allaqachon bir marta o'zgartirilgan.", null=True, verbose_name="nom o'zgartirilgan"),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('oldingi_username'), condition=models.Q(('oldingi_username', ''), _negated=True), name='accounts_user_oldingi_username_ci_uniq', violation_error_message='Bu foydalanuvchi nomi band.'),
        ),
    ]
