# Generated by Django 6.1 on 2026-08-29 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_oldingi_username_user_username_ozgartirilgan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ochirilgan_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text="To'ldirilgan bo'lsa: shaxsiy ma'lumot tozalangan, kontent qolgan.", null=True, verbose_name="hisob o'chirilgan"),
        ),
        migrations.CreateModel(
            name='MalumotEksporti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[('navbatda', 'Tayyorlanmoqda'), ('tayyor', 'Tayyor'), ('xato', 'Xato')], default='navbatda', max_length=16, verbose_name='holat')),
                ('malumot', models.JSONField(blank=True, editable=False, null=True, verbose_name="ma'lumot")),
                ('xato', models.TextField(blank=True, editable=False, verbose_name='xato')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="so'ralgan")),
                ('tayyor_at', models.DateTimeField(blank=True, null=True, verbose_name="tayyor bo'lgan")),
                ('muddat', models.DateTimeField(db_index=True, verbose_name='amal qilish muddati')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eksportlar', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "ma'lumot eksporti",
                'verbose_name_plural': "ma'lumot eksportlari",
                'ordering': ('-created_at',),
            },
        ),
    ]
