# Generated by Django 6.1 on 2026-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ochirilgan_at_malumoteksporti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rozilik_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='rozilik sanasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='rozilik_versiyasi',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='rozilik versiyasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='yosh_tasdigi_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="yosh tasdig'i"),
        ),
    ]
