# Generated by Django 6.1 on 2026-08-29 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_rozilik_at_user_rozilik_versiyasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='bloklangan vaqt')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloklanganlari', to=settings.AUTH_USER_MODEL, verbose_name='kim bloklangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloklaganlari', to=settings.AUTH_USER_MODEL, verbose_name='kim bloklagan')),
            ],
            options={
                'verbose_name': 'foydalanuvchi bloki',
                'verbose_name_plural': 'foydalanuvchi bloklari',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'blocked'), name='userblock_uniq', violation_error_message='Bu foydalanuvchi allaqachon bloklangan.'), models.CheckConstraint(condition=models.Q(('user', models.F('blocked')), _negated=True), name='userblock_ozini_bloklamaydi', violation_error_message="O'zingizni bloklay olmaysiz.")],
            },
        ),
    ]
