# Generated by Django 6.1 on 2026-08-29 21:27

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userblock'),
        ('complaints', '0004_complaint_inqiroz_aniqlandi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, help_text='Nechchi yildan beri shu sohada ishlaysiz.', validators=[django.core.validators.MaxValueValidator(70)], verbose_name='tajriba (yil)')),
                ('kasbiy_tavsif', models.TextField(blank=True, help_text='Malakangiz haqida: qayerda ishlaysiz, nimaga ixtisoslashgansiz.', max_length=1000, verbose_name='kasbiy tavsif')),
                ('verification_status', models.CharField(choices=[('qoralama', 'Qoralama — hali topshirilmagan'), ('kutilmoqda', "Ko'rib chiqilmoqda"), ('tasdiqlangan', 'Tasdiqlangan'), ('rad_etilgan', 'Rad etilgan')], db_index=True, default='qoralama', max_length=16, verbose_name='tasdiqlash holati')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='tasdiqlangan vaqt')),
                ('topshirilgan_at', models.DateTimeField(blank=True, null=True, verbose_name='topshirilgan vaqt')),
                ('rad_sababi', models.CharField(blank=True, help_text="Foydalanuvchiga KO'RSATILADI — u nima tuzatishni bilishi kerak.", max_length=300, verbose_name='rad etish sababi')),
                ('hujjat', models.FileField(blank=True, help_text="Diplom, litsenziya yoki ish joyidan ma'lumotnoma.", null=True, storage=apps.accounts.models.maxfiy_saqlash, upload_to=apps.accounts.models.ekspert_hujjati_yoli, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='tasdiqlovchi hujjat')),
                ('contact_visible', models.BooleanField(default=False, help_text="PRO obunachilar siz bilan bog'lana olishi uchun.", verbose_name="aloqa ma'lumotim ko'rinsin")),
                ('pro_until', models.DateTimeField(blank=True, null=True, verbose_name='PRO muddati')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ekspertlar', to='complaints.category', verbose_name='soha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ekspert_profili', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasdiqlagan_ekspertlari', to=settings.AUTH_USER_MODEL, verbose_name='kim tasdiqladi')),
            ],
            options={
                'verbose_name': 'ekspert profili',
                'verbose_name_plural': 'ekspert profillari',
                'ordering': ('-topshirilgan_at', '-created_at'),
                'indexes': [models.Index(fields=['verification_status', 'topshirilgan_at'], name='ekspert_navbat_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'tasdiqlangan'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='ekspert_tasdiq_vaqtsiz_bolmaydi', violation_error_message="Tasdiqlangan profilda tasdiq vaqti bo'lishi shart.")],
            },
        ),
    ]
