# Generated by Django 6.1 on 2026-09-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_expertprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bloklandi',
            field=models.BooleanField(default=False, help_text="Telegram 403 qaytarganda avtomatik qo'yiladi (D5-T2).", verbose_name='Telegram boti bloklangan'),
        ),
    ]
