# Generated by Django 6.1 on 2026-09-06 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0002_solution_inqiroz_aniqlandi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktSorovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Javob kutilmoqda'), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], db_index=True, default='kutilmoqda', max_length=16, verbose_name='holat')),
                ('javob_at', models.DateTimeField(blank=True, null=True, verbose_name='javob berilgan vaqt')),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kontakt_sorovi', to='solutions.solution', verbose_name='qabul qilingan yechim')),
                ('soragan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuborgan_kontakt_sorovlari', to=settings.AUTH_USER_MODEL, verbose_name="kim so'radi")),
            ],
            options={
                'verbose_name': "kontakt so'rovi",
                'verbose_name_plural': "kontakt so'rovlari",
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Suhbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('yopilgan_at', models.DateTimeField(blank=True, null=True, verbose_name='yopilgan vaqt')),
                ('sorov', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suhbat', to='suhbat.kontaktsorovi', verbose_name="kontakt so'rovi")),
                ('yopgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yopgan_suhbatlari', to=settings.AUTH_USER_MODEL, verbose_name='kim yopdi')),
            ],
            options={
                'verbose_name': 'suhbat',
                'verbose_name_plural': 'suhbatlar',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name="o'chirilgan")),
                ('moderation_status', models.CharField(choices=[('visible', "Ko'rinadi"), ('pending', 'Tekshiruvda'), ('hidden', 'Yashirilgan'), ('removed', 'Qoidabuzarlik uchun olib tashlangan')], db_index=True, default='visible', max_length=16, verbose_name='moderatsiya holati')),
                ('moderation_note', models.CharField(blank=True, help_text="Foydalanuvchiga ko'rsatiladi — sababsiz yashirish shikoyat keltiradi.", max_length=300, verbose_name='moderator izohi')),
                ('inqiroz_aniqlandi', models.BooleanField(db_index=True, default=False, editable=False, help_text="Avtomatik aniqlash (D2-T6). Ko'rinishga TA'SIR QILMAYDI.", verbose_name='inqiroz belgisi aniqlangan')),
                ('content', models.TextField(max_length=2000, verbose_name='xabar matni')),
                ('okilgan_at', models.DateTimeField(blank=True, null=True, verbose_name="o'qilgan vaqt")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suhbat_xabarlari', to=settings.AUTH_USER_MODEL, verbose_name='muallif')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="kim o'chirdi")),
                ('suhbat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='suhbat.suhbat', verbose_name='suhbat')),
            ],
            options={
                'verbose_name': 'suhbat xabari',
                'verbose_name_plural': 'suhbat xabarlari',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['suhbat', 'created_at'], name='xabar_suhbat_idx')],
            },
        ),
    ]
