# Generated by Django 6.1 on 2026-08-27 20:13

import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(help_text="URL'da ishlatiladi: /?category=moliya", max_length=60, unique=True, verbose_name='URL nomi')),
                ('icon', models.CharField(choices=[('briefcase', 'Chamadon — karyera'), ('heart', 'Yurak — munosabatlar'), ('money', 'Pul — moliya'), ('graduation', "Qalpoq — ta'lim"), ('pulse', "Puls — sog'liq"), ('home', 'Uy — uy-joy'), ('scale', 'Tarozi — huquq'), ('dots', 'Nuqtalar — boshqa')], default='dots', max_length=20, verbose_name='ikonka')),
                ('description', models.CharField(blank=True, help_text="Kategoriyalar sahifasida kartochka ostida ko'rinadi.", max_length=200, verbose_name='tavsif')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Kichik raqam — yuqorida.', verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa yangi post uchun tanlab bo'lmaydi, eskilari qoladi.", verbose_name='faol')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name="o'chirilgan")),
                ('moderation_status', models.CharField(choices=[('visible', "Ko'rinadi"), ('pending', 'Tekshiruvda'), ('hidden', 'Yashirilgan'), ('removed', 'Qoidabuzarlik uchun olib tashlangan')], db_index=True, default='visible', max_length=16, verbose_name='moderatsiya holati')),
                ('moderation_note', models.CharField(blank=True, help_text="Foydalanuvchiga ko'rsatiladi — sababsiz yashirish shikoyat keltiradi.", max_length=300, verbose_name='moderator izohi')),
                ('upvotes_cached', models.PositiveIntegerField(default=0, editable=False, verbose_name='foydali ovozlar')),
                ('downvotes_cached', models.PositiveIntegerField(default=0, editable=False, verbose_name='foydali emas ovozlar')),
                ('score_cached', models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('upvotes_cached'), '-', models.F('downvotes_cached')), output_field=models.IntegerField(), verbose_name='ball')),
                ('title', models.CharField(max_length=150, verbose_name='sarlavha')),
                ('description', models.TextField(max_length=5000, verbose_name='tavsif')),
                ('slug', models.SlugField(editable=False, max_length=170, verbose_name='URL nomi')),
                ('generation_tag', models.CharField(blank=True, choices=[('genz', 'Gen Z'), ('millennial', 'Millennial'), ('boomer', 'Boomer')], db_index=True, help_text="Ixtiyoriy — hamma ham o'zini avlodga bog'lamaydi.", max_length=12, verbose_name='avlod')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Yoqilsa muallif hech qayerda ko'rsatilmaydi.", verbose_name='anonim')),
                ('anon_handle', models.CharField(blank=True, editable=False, help_text='Hozircha ishlatilmaydi (ochiq qaror Q2).', max_length=40, verbose_name='anonim taxallus')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('solved', 'Yechilgan'), ('closed', 'Yopilgan')], db_index=True, default='open', max_length=10, verbose_name='holat')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rishlar")),
                ('solutions_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='yechimlar soni')),
                ('has_expert_answer', models.BooleanField(default=False, editable=False, verbose_name='ekspert javob bergan')),
                ('hot_score', models.FloatField(db_index=True, default=0.0, verbose_name='qaynoqlik')),
            ],
            options={
                'verbose_name': 'muammo',
                'verbose_name_plural': 'muammolar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('value', models.SmallIntegerField(choices=[(1, 'Foydali'), (-1, 'Foydali emas')], verbose_name='qiymat')),
            ],
            options={
                'verbose_name': 'muammo ovozi',
                'verbose_name_plural': 'muammo ovozlari',
            },
        ),
    ]
