# Generated by Django 6.1 on 2026-08-28 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='complaints.complaint', verbose_name='muammo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'saqlangan muammo',
                'verbose_name_plural': 'saqlangan muammolar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_user_vaqt_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'complaint'), name='savedcomplaint_user_target_uniq')],
            },
        ),
    ]
