# Generated by Django 6.1 on 2026-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_qidiruv_transliteratsiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='og_rasm',
            field=models.ImageField(blank=True, editable=False, help_text="Avtomatik yasaladi (D4-T4). Qo'lda yuklanmaydi.", upload_to='og/', verbose_name='OG rasm'),
        ),
    ]
