# Generated by Django 6.1 on 2026-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_og_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='kanalga_yuborilgan_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='kanalga yuborilgan'),
        ),
    ]
