# Generated by Django 6.1 on 2026-08-27 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(choices=[('solution_accepted', 'Yechim qabul qilindi'), ('solution_unaccepted', 'Yechim qabuli bekor qilindi')], max_length=32, verbose_name='sabab')),
                ('points', models.SmallIntegerField(help_text="Manfiy bo'lishi mumkin — teskari (kompensatsion) yozuv.", verbose_name='ball')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karma_events', to='solutions.solution', verbose_name='yechim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_events', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'karma hodisasi',
                'verbose_name_plural': 'karma hodisalari',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='karma_user_vaqt_idx')],
            },
        ),
    ]
