# Generated by Django 6.1 on 2026-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmaevent',
            name='reason',
            field=models.CharField(choices=[('solution_accepted', 'Yechim qabul qilindi'), ('solution_unaccepted', 'Yechim qabuli bekor qilindi'), ('solution_upvoted', 'Yechimga ovoz berildi'), ('solution_upvote_olindi', 'Yechimdagi ovoz olindi'), ('kontent_olib_tashlandi', 'Kontent olib tashlandi — karma qaytarildi'), ('kontent_tiklandi', 'Kontent tiklandi — karma qaytarib berildi')], max_length=32, verbose_name='sabab'),
        ),
    ]
