# Generated by Django 6.1 on 2026-08-29 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_karmaevent_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('slug', models.SlugField(help_text='Barqaror kalit — fixture va testlar shunga tayanadi.', unique=True, verbose_name='kalit')),
                ('nom', models.CharField(max_length=60, verbose_name='nom')),
                ('tavsif', models.CharField(help_text="QULFLANGAN holatda ko'rsatiladi: «10 ta yechimingiz qabul qilinsa ochiladi». Bu bezak emas — u xulqni yo'naltiradi.", max_length=160, verbose_name='ochilish sharti')),
                ('ikonka', models.CharField(choices=[('check', 'Belgi — birinchi qadam'), ('bolt', 'Chaqmoq — karma'), ('chat', 'Suhbat — yechimlar'), ('shield', 'Qalqon — ishonch'), ('star', 'Yulduz — sifat'), ('flame', 'Alanga — faollik')], default='check', max_length=16, verbose_name='ikonka')),
                ('metrika', models.CharField(choices=[('karma', 'Karma'), ('yechimlar', 'Yozilgan yechimlar'), ('qabul_qilingan', 'Qabul qilingan yechimlar'), ('dardlar', 'Yozilgan dardlar'), ('olingan_ovoz', 'Yechimlarga olingan ovoz')], max_length=20, verbose_name="o'lchov")),
                ('chegara', models.PositiveIntegerField(help_text='Shu qiymatga yetganda nishon beriladi.', verbose_name='chegara')),
                ('tartib', models.PositiveSmallIntegerField(default=100, verbose_name='tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='faol')),
            ],
            options={
                'verbose_name': 'nishon',
                'verbose_name_plural': 'nishonlar',
                'ordering': ('tartib', 'chegara', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('chegara__gt', 0)), name='nishon_chegara_musbat', violation_error_message="Chegara noldan katta bo'lishi kerak.")],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berilgan_at', models.DateTimeField(auto_now_add=True, verbose_name='berilgan vaqt')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egalari', to='gamification.badge', verbose_name='nishon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nishonlari', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'foydalanuvchi nishoni',
                'verbose_name_plural': 'foydalanuvchi nishonlari',
                'ordering': ('-berilgan_at',),
                'indexes': [models.Index(fields=['user', '-berilgan_at'], name='nishon_user_vaqt_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='userbadge_uniq', violation_error_message='Bu nishon allaqachon berilgan.')],
            },
        ),
    ]
