# Generated by Django 6.1 on 2026-08-28 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0003_savedcomplaint'),
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('reason', models.CharField(choices=[('spam', 'Spam yoki reklama'), ('haqorat', 'Haqorat yoki nafrat'), ('shaxsiy', "Shaxsiy ma'lumot oshkor qilingan"), ('xavf', "O'ziga yoki boshqaga zarar yetkazish xavfi"), ('boshqa', 'Boshqa sabab')], max_length=16, verbose_name='sabab')),
                ('comment', models.TextField(blank=True, help_text='Ixtiyoriy — moderatorga kontekst beradi.', max_length=1000, verbose_name='izoh')),
                ('status', models.CharField(choices=[('ochiq', "Ko'rib chiqilmagan"), ('hal_qilindi', "Qabul qilindi (chora ko'rildi)"), ('rad_etildi', "Rad etildi (qoidabuzarlik yo'q)")], db_index=True, default='ochiq', max_length=16, verbose_name='holat')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='hal qilingan vaqt')),
                ('resolution_note', models.CharField(blank=True, help_text='Nima qilindi va nega. D2-T7 auditiga tushadi.', max_length=300, verbose_name='qaror izohi')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='complaints.complaint', verbose_name='muammo')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='shikoyatchi')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim hal qildi')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='solutions.solution', verbose_name='yechim')),
            ],
            options={
                'verbose_name': 'shikoyat',
                'verbose_name_plural': 'shikoyatlar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='report_navbat_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('complaint__isnull', False), ('solution__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', False)), _connector='OR'), name='report_aynan_bitta_maqsad', violation_error_message="Shikoyat aynan bitta obyektga tegishli bo'lishi kerak."), models.UniqueConstraint(condition=models.Q(('complaint__isnull', False)), fields=('reporter', 'complaint'), name='report_bir_muammoga_bir_marta', violation_error_message='Siz bu postga allaqachon shikoyat qilgansiz.'), models.UniqueConstraint(condition=models.Q(('solution__isnull', False)), fields=('reporter', 'solution'), name='report_bir_yechimga_bir_marta', violation_error_message='Siz bu yechimga allaqachon shikoyat qilgansiz.')],
            },
        ),
    ]
