# Generated by Django 6.1 on 2026-08-28 23:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_savedcomplaint'),
        ('moderation', '0001_initial'),
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('action', models.CharField(choices=[('rad_etish', "Qoidabuzarlik yo'q"), ('ogohlantirish', 'Ogohlantirish (kontent qoladi)'), ('yashirish', 'Yashirish'), ('olib_tashlash', 'Olib tashlash'), ('bekor_qilish', 'Oldingi qaror bekor qilindi')], max_length=16, verbose_name='chora')),
                ('note', models.CharField(blank=True, help_text="Muallifga KO'RSATILADI — sababsiz chora shikoyat keltiradi.", max_length=300, verbose_name='izoh')),
                ('oldingi_holat', models.CharField(blank=True, choices=[('visible', "Ko'rinadi"), ('pending', 'Tekshiruvda'), ('hidden', 'Yashirilgan'), ('removed', 'Qoidabuzarlik uchun olib tashlangan')], editable=False, help_text='Bekor qilish kontentni aynan shu holatga qaytaradi.', max_length=16, verbose_name='chora oldidagi holat')),
                ('bekor_qiladi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bekor_qilishlar', to='moderation.moderationaction', verbose_name='qaysi qarorni bekor qiladi')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='complaints.complaint', verbose_name='muammo')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='solutions.solution', verbose_name='yechim')),
                ('target_author', models.ForeignKey(blank=True, help_text="Denormalizatsiya: kontent o'chsa ham chora kimga tegishli ekani qoladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olingan_choralar', to=settings.AUTH_USER_MODEL, verbose_name='kontent muallifi')),
            ],
            options={
                'verbose_name': 'moderator chorasi',
                'verbose_name_plural': 'moderator choralari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='yopgan_chora',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yopilgan_shikoyatlar', to='moderation.moderationaction', verbose_name='yopgan chora'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_author', 'action'], name='action_muallif_chora_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complaint__isnull', False), ('solution__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', False)), _connector='OR'), name='action_aynan_bitta_maqsad', violation_error_message="Chora aynan bitta obyektga tegishli bo'lishi kerak."),
        ),
    ]
