# Generated by Django 6.1 on 2026-08-29 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationaction_report_yopgan_chora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqt')),
                ('actor_nomi', models.CharField(blank=True, help_text="Hisob o'chirilsa ham qoladi. Bo'sh = tizim.", max_length=150, verbose_name='kim (nusxa)')),
                ('action', models.CharField(choices=[('kontent_chora', 'Kontent ustidan chora'), ('chora_bekor', 'Chora bekor qilindi'), ('shikoyat_yopildi', 'Shikoyat yopildi'), ('avtomatik_belgi', 'Avtomatik filtr belgiladi')], max_length=32, verbose_name='harakat')),
                ('obyekt', models.CharField(help_text='Masalan: «muammo #12», «shikoyat #4».', max_length=100, verbose_name='obyekt')),
                ('izoh', models.TextField(blank=True, verbose_name='sabab / izoh')),
                ('malumot', models.JSONField(blank=True, default=dict, verbose_name="qo'shimcha")),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_yozuvlari', to=settings.AUTH_USER_MODEL, verbose_name='kim')),
            ],
            options={
                'verbose_name': 'audit yozuvi',
                'verbose_name_plural': 'audit jurnali',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_harakat_idx'), models.Index(fields=['actor', '-created_at'], name='audit_kim_idx')],
            },
        ),
    ]
