# Generated by Django 6.1 on 2026-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('kontent_chora', 'Kontent ustidan chora'), ('chora_bekor', 'Chora bekor qilindi'), ('shikoyat_yopildi', 'Shikoyat yopildi'), ('avtomatik_belgi', 'Avtomatik filtr belgiladi'), ('inqiroz_aniqlandi', 'Inqiroz belgisi aniqlandi'), ('hisob_ochirildi', "Hisob o'chirildi"), ('foydalanuvchi_cheklandi', 'Foydalanuvchi cheklandi'), ('cheklov_yechildi', 'Cheklov yechildi'), ('ekspert_tasdiqlandi', 'Ekspert tasdiqlandi'), ('ekspert_rad_etildi', 'Ekspert arizasi rad etildi'), ('ekspert_bekor_qilindi', 'Ekspert maqomi bekor qilindi')], max_length=32, verbose_name='harakat'),
        ),
    ]
