# Generated by Django 6.1 on 2026-09-06 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_kanal_belgisi'),
        ('moderation', '0007_alter_auditlog_action'),
        ('solutions', '0002_solution_inqiroz_aniqlandi'),
        ('suhbat', '0001_suhbat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moderationaction',
            name='action_aynan_bitta_maqsad',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='report_aynan_bitta_maqsad',
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='xabar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='suhbat.xabar', verbose_name='suhbat xabari'),
        ),
        migrations.AddField(
            model_name='report',
            name='xabar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='suhbat.xabar', verbose_name='suhbat xabari'),
        ),
        migrations.AddConstraint(
            model_name='moderationaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complaint__isnull', False), ('solution__isnull', True), ('xabar__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', False), ('xabar__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', True), ('xabar__isnull', False)), _connector='OR'), name='action_aynan_bitta_maqsad', violation_error_message="Chora aynan bitta obyektga tegishli bo'lishi kerak."),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complaint__isnull', False), ('solution__isnull', True), ('xabar__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', False), ('xabar__isnull', True)), models.Q(('complaint__isnull', True), ('solution__isnull', True), ('xabar__isnull', False)), _connector='OR'), name='report_aynan_bitta_maqsad', violation_error_message="Shikoyat aynan bitta obyektga tegishli bo'lishi kerak."),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('xabar__isnull', False)), fields=('reporter', 'xabar'), name='report_bir_xabarga_bir_marta', violation_error_message='Siz bu xabarga allaqachon shikoyat qilgansiz.'),
        ),
    ]
