# Generated by Django 6.1 on 2026-09-06 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('plan', models.CharField(choices=[('pro', 'PRO')], default='pro', max_length=16, verbose_name='reja')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Muddati tugagan')], db_index=True, default='faol', max_length=16, verbose_name='holat')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='boshlangan vaqt')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='tugash vaqti')),
                ('auto_renew', models.BooleanField(default=False, help_text="O'chirilsa obuna joriy muddat oxirida tugaydi.", verbose_name='avtomatik yangilanadi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obuna', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'obuna',
                'verbose_name_plural': 'obunalar',
                'ordering': ('-expires_at', '-id'),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='obuna_muddat_idx')],
            },
        ),
    ]
