# Generated by Django 6.1 on 2026-09-07 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_obuna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('maqsad', models.CharField(choices=[('obuna', 'PRO obuna')], default='obuna', max_length=16, verbose_name='maqsad')),
                ('provayder', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=16, verbose_name='provayder')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='summa')),
                ('holat', models.CharField(choices=[('yangi', 'Yaratildi'), ('tayyor', 'Tasdiqlashga tayyor'), ('tolandi', "To'landi"), ('bekor', 'Bekor qilindi')], db_index=True, default='yangi', max_length=16, verbose_name='holat')),
                ('provayder_trans_id', models.CharField(blank=True, help_text='Click: click_trans_id. Idempotentlik kaliti.', max_length=64, verbose_name='provayder tranzaksiyasi')),
                ('tolangan_at', models.DateTimeField(blank=True, null=True, verbose_name="to'langan vaqt")),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='izoh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "to'lov",
                'verbose_name_plural': "to'lovlar",
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TolovSorovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='vaqt')),
                ('provayder', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=16, verbose_name='provayder')),
                ('amal', models.CharField(help_text='Click: prepare / complete. Payme: metod nomi.', max_length=32, verbose_name='amal')),
                ('merchant_trans_id', models.CharField(blank=True, max_length=64, verbose_name='buyurtma (nusxa)')),
                ('provayder_trans_id', models.CharField(blank=True, max_length=64, verbose_name='provayder tranzaksiyasi')),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('imzo_togrimi', models.BooleanField(default=False, verbose_name="imzo to'g'ri")),
                ('natija', models.IntegerField(default=0, verbose_name='qaytarilgan kod')),
                ('xom', models.JSONField(blank=True, default=dict, verbose_name="kelgan ma'lumot")),
                ('javob', models.JSONField(blank=True, default=dict, verbose_name='qaytarilgan javob')),
                ('tolov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorovlar', to='payments.tolov', verbose_name="to'lov")),
            ],
            options={
                'verbose_name': "to'lov so'rovi",
                'verbose_name_plural': "to'lov so'rovlari jurnali",
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='tolov',
            index=models.Index(fields=['user', '-created_at'], name='tolov_odam_idx'),
        ),
        migrations.AddIndex(
            model_name='tolov',
            index=models.Index(fields=['holat', '-created_at'], name='tolov_holat_idx'),
        ),
        migrations.AddConstraint(
            model_name='tolov',
            constraint=models.UniqueConstraint(condition=models.Q(('provayder_trans_id', ''), _negated=True), fields=('provayder', 'provayder_trans_id'), name='tolov_provayder_trans_noyob'),
        ),
        migrations.AddIndex(
            model_name='tolovsorovi',
            index=models.Index(fields=['provayder', '-created_at'], name='tolovjurnal_prov_idx'),
        ),
        migrations.AddIndex(
            model_name='tolovsorovi',
            index=models.Index(fields=['tolov', '-created_at'], name='tolovjurnal_tolov_idx'),
        ),
    ]
