# Generated by Django 6.1 on 2026-09-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_tolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='bekor_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan vaqt'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='bekor_kodi',
            field=models.IntegerField(blank=True, null=True, verbose_name='bekor sababi (provayder)'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='berilgan_kun',
            field=models.IntegerField(blank=True, null=True, verbose_name='berilgan kun'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='tayyorlangan_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="provayder ro'yxatga oldi"),
        ),
    ]
