# Generated by Django 6.1 on 2026-09-11 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_kanal_belgisi'),
        ('payments', '0003_tolov_hayot_sikli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='maqsad',
            field=models.CharField(choices=[('obuna', 'PRO obuna'), ('boost', "Postni ko'tarish")], default='obuna', max_length=16, verbose_name='maqsad'),
        ),
        migrations.CreateModel(
            name='BoostOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='boshlanishi')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='tugashi')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boostlar', to='complaints.complaint', verbose_name='muammo')),
                ('tolov', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boost', to='payments.tolov', verbose_name="to'lov")),
            ],
            options={
                'verbose_name': "ko'tarish",
                'verbose_name_plural': "ko'tarishlar",
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['ends_at', 'starts_at'], name='boost_faol_idx')],
            },
        ),
    ]
