# Generated by Django 6.1 on 2026-08-27 20:13

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name="o'chirilgan")),
                ('moderation_status', models.CharField(choices=[('visible', "Ko'rinadi"), ('pending', 'Tekshiruvda'), ('hidden', 'Yashirilgan'), ('removed', 'Qoidabuzarlik uchun olib tashlangan')], db_index=True, default='visible', max_length=16, verbose_name='moderatsiya holati')),
                ('moderation_note', models.CharField(blank=True, help_text="Foydalanuvchiga ko'rsatiladi — sababsiz yashirish shikoyat keltiradi.", max_length=300, verbose_name='moderator izohi')),
                ('upvotes_cached', models.PositiveIntegerField(default=0, editable=False, verbose_name='foydali ovozlar')),
                ('downvotes_cached', models.PositiveIntegerField(default=0, editable=False, verbose_name='foydali emas ovozlar')),
                ('score_cached', models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('upvotes_cached'), '-', models.F('downvotes_cached')), output_field=models.IntegerField(), verbose_name='ball')),
                ('content', models.TextField(max_length=5000, verbose_name='yechim matni')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Yoqilsa muallif ko'rsatilmaydi, lekin karma o'ziga yoziladi.", verbose_name='anonim')),
                ('is_accepted', models.BooleanField(default=False, help_text='Muammo muallifi tanlaydi. Bitta muammoda faqat bitta.', verbose_name='qabul qilingan')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='qabul qilingan vaqt')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to=settings.AUTH_USER_MODEL, verbose_name='muallif')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='complaints.complaint', verbose_name='muammo')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="kim o'chirdi")),
            ],
            options={
                'verbose_name': 'yechim',
                'verbose_name_plural': 'yechimlar',
                'ordering': ('-score_cached', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SolutionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('value', models.SmallIntegerField(choices=[(1, 'Foydali'), (-1, 'Foydali emas')], verbose_name='qiymat')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='solutions.solution', verbose_name='yechim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'yechim ovozi',
                'verbose_name_plural': 'yechim ovozlari',
            },
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['complaint', 'score_cached'], name='solution_compl_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_accepted', True)), fields=('complaint',), name='solution_one_accepted_per_complaint', violation_error_message='Bu muammoda allaqachon qabul qilingan yechim bor.'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('is_accepted', False)), models.Q(('accepted_at__isnull', False), ('is_accepted', True)), _connector='OR'), name='solution_accepted_at_bilan_birga'),
        ),
        migrations.AddConstraint(
            model_name='solutionvote',
            constraint=models.UniqueConstraint(fields=('user', 'solution'), name='solutionvote_user_target_uniq', violation_error_message='Bu yechimga allaqachon ovoz bergansiz.'),
        ),
    ]
