# Generated by Django 6.1 on 2026-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='inqiroz_aniqlandi',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text="Avtomatik aniqlash (D2-T6). Ko'rinishga TA'SIR QILMAYDI.", verbose_name='inqiroz belgisi aniqlangan'),
        ),
    ]
