# Generated by Django 6.1 on 2026-09-13 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0008_kanal_belgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('nom', models.CharField(help_text="Faqat adminda ko'rinadi (masalan: «Uy-joy — Golden House, sentabr»).", max_length=60, verbose_name='ichki nom')),
                ('sarlavha', models.CharField(max_length=60, verbose_name='sarlavha')),
                ('matn', models.CharField(max_length=140, verbose_name='matn')),
                ('manzil', models.URLField(max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='havola')),
                ('tugma_matni', models.CharField(default='Batafsil', max_length=24, verbose_name='tugma matni')),
                ('boshlanish', models.DateTimeField(blank=True, null=True, verbose_name='boshlanishi')),
                ('tugash', models.DateTimeField(blank=True, null=True, verbose_name='tugashi')),
                ('faolmi', models.BooleanField(default=False, help_text="Yoqilmaguncha saytda ko'rinmaydi.", verbose_name='faol')),
                ('korsatishlar', models.PositiveIntegerField(default=0, editable=False, verbose_name="ko'rsatishlar")),
                ('bosishlar', models.PositiveIntegerField(default=0, editable=False, verbose_name='bosishlar')),
                ('kategoriya', models.ForeignKey(blank=True, help_text="Bo'sh qoldirilsa — barcha kategoriyalarda ko'rinadi.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reklamalar', to='complaints.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'reklama',
                'verbose_name_plural': 'reklamalar',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['faolmi', 'tugash'], name='reklama_faol_idx')],
            },
        ),
    ]
