# Generated by Django 6.1 on 2026-09-06 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0007_og_rasm'),
        ('solutions', '0002_solution_inqiroz_aniqlandi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('turi', models.CharField(choices=[('yangi_yechim', 'Muammoingizga yechim yozildi'), ('yechim_qabul', 'Yechimingiz qabul qilindi')], db_index=True, max_length=20, verbose_name='turi')),
                ('okilgan_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name="o'qilgan")),
                ('actor', models.ForeignKey(blank=True, help_text="Anonim manbada BO'SH — sabab model docstring'ida.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='kim')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='complaints.complaint', verbose_name='muammo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to=settings.AUTH_USER_MODEL, verbose_name='kimga')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solutions.solution', verbose_name='yechim')),
            ],
            options={
                'verbose_name': 'bildirishnoma',
                'verbose_name_plural': 'bildirishnomalar',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'okilgan_at'], name='bildirishnoma_oqilm_idx')],
            },
        ),
    ]
