# Generated by Django 6.1 on 2026-09-06 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BildirishnomaSozlamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('turlar', models.JSONField(blank=True, default=dict, help_text='{tur: yoqilganmi}. Berilmagan tur standart holatda.', verbose_name="turlar bo'yicha")),
                ('jim_soatlar', models.BooleanField(default=True, help_text='Kechasi kelgan xabar ertalabgacha kechiktiriladi.', verbose_name='jim soatlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnoma_sozlamasi', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'bildirishnoma sozlamasi',
                'verbose_name_plural': 'bildirishnoma sozlamalari',
            },
        ),
    ]
