# Generated by Django 6.1 on 2026-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sozlama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='turi',
            field=models.CharField(choices=[('yangi_yechim', 'Muammoingizga yechim yozildi'), ('yechim_qabul', 'Yechimingiz qabul qilindi'), ('dayjest', 'Sohangizdagi javobsiz savollar')], db_index=True, max_length=20, verbose_name='turi'),
        ),
    ]
