# Generated by Django 6.1 on 2026-09-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_dayjest_turi'),
        ('suhbat', '0001_suhbat'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kontakt_sorovi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to='suhbat.kontaktsorovi', verbose_name="kontakt so'rovi"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='turi',
            field=models.CharField(choices=[('yangi_yechim', 'Muammoingizga yechim yozildi'), ('yechim_qabul', 'Yechimingiz qabul qilindi'), ('dayjest', 'Sohangizdagi javobsiz savollar'), ('kontakt_sorovi', "Shaxsiy suhbat so'rovi"), ('kontakt_javobi', "Suhbat so'rovingizga javob"), ('yangi_xabar', 'Suhbatda yangi xabar')], db_index=True, max_length=20, verbose_name='turi'),
        ),
    ]
